// Mocks generated by Mockito 5.4.4 from annotations
// in adonanku_frontend/test/views/login_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:adonanku_frontend/models/login_model.dart' as _i5;
import 'package:adonanku_frontend/models/regist_model.dart' as _i4;
import 'package:adonanku_frontend/services/auth_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.RegisterModel?> register({
    required String? nama,
    required String? username,
    required String? email,
    required String? password,
    required String? passwordConfirmation,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #nama: nama,
            #username: username,
            #email: email,
            #password: password,
            #passwordConfirmation: passwordConfirmation,
          },
        ),
        returnValue: _i3.Future<_i4.RegisterModel?>.value(),
      ) as _i3.Future<_i4.RegisterModel?>);

  @override
  _i3.Future<_i5.LoginResponseModel?> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i3.Future<_i5.LoginResponseModel?>.value(),
      ) as _i3.Future<_i5.LoginResponseModel?>);
}
